name: .NET

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
              
    - name: Build & Restore
      run: dotnet build ./src/Thoth.Core/Thoth.Core.csproj -c Release -o out

    - name: Package
      run: dotnet pack ./src/Thoth.Core/Thoth.Core.csproj --no-build -c Release -o out 

    - name: Push on Nuget
      run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json"